version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
    commands:
      - echo 'install'
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Logging into Amazon ECR'
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 836449767160.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    on-failure: ABORT
    commands:
      - cp .env.prod .env
      - docker build -t prod-laravel-api .
      - docker tag prod-laravel-api:latest 836449767160.dkr.ecr.ap-southeast-1.amazonaws.com/prod-laravel-api:latest
  post_build:
    on-failure: ABORT
    commands:
      - docker images ls -a
      - docker push 836449767160.dkr.ecr.ap-southeast-1.amazonaws.com/prod-laravel-api:latest